name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * 0' # every Sunday
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Add upstream
        run: |
          git remote add upstream https://github.com/open-webui/open-webui.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: 'Sync from upstream'
            branch: 'sync-upstream'
            title: 'Sync from upstream'
            body: 'This PR syncs changes from the upstream repository.'
            base: 'main'
